### ISSUE TITLE
Tutorial: fix remaining TODO items

### ISSUE THREAD

**Issue by x1B** [LaxarJS/shop-demo#44]
The tutorials contain several TODO items, also mentioned in #43.
These are disguised as HTML comments, and cover the following:

- [ ] add wiring diagrams to the individual steps
- [ ] add screen shots in some places
- [x] check if the Yeoman generator dialogue is correct

_Edit:_ new issue for the 3 missing diagrams and 1 remaining screenshot

**Comment by x1B** [comment]
@jonaswjs passing this to you. As discussed, the feature branch already contains the changes for the generator.

**Comment by x1B** [comment]
@jonaswjs I'll create a new issue about the missing images so that we can merge the parts that we have now before tagging RC0.

**Comment by x1B** [comment]
Implemented on `master-2.x` (`v2.0.0`).
